name: How About this Test name
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a07553'
    - '#e0be91'
    - '#31221b'
    - '#ffe4be'
    - '#584849'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
