name: How About this Test name
favicon: null
layout_spectrum: 0.74834
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff3300'
    - '#ffc000'
    - '#00b050'
    - '#3475cd'
    - '#b8cfed'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
