name: How About this Test name
favicon: null
layout_spectrum: 0.9541884574573487
typography_spectrum: 0.7312827478162944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8991792877204716
  lightness: 0.7358820994850248
  saturation: 0.8098229565657675
  rhythmicContrast: 0.9446803817991167
purpose: []
