name: How About this Test name
favicon: null
layout_spectrum: 0.47496
typography_spectrum: 0.5172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff3300'
    - '#ffc000'
    - '#00b050'
    - '#3475cd'
    - '#b8cfed'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
