name: How About this Test name
favicon: null
layout_spectrum: 0.73777
typography_spectrum: 0.06074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f8f1'
    - '#352d22'
    - '#8d8d83'
    - '#6a7567'
    - '#b6c7b7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
